/* CONFESSION ACTION TYPES */
const CREATE_CONFESSION = "CREATE_CONFESSION";
const SET_CATEGORY_FILTER = "SET_CATEGORY_FILTER";

/* USER ACTION TYPES */
const SET_USER = "SET_USER";

export { CREATE_CONFESSION, SET_CATEGORY_FILTER, SET_USER };
